[package]
name = "tpcp"
version = "0.2.0"
description = "Easily create a new project from a template"
edition = "2021"
authors = ["Alejandro Gonzalvo <alejandrogonhid@gmail.com>"]
readme = "README.md"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
